name: lpls
description: "Launchpad lightshow software"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  archive: ^4.0.7
  audio_in_app: ^2.1.1
  audioplayers: ^5.2.1
  desktop_drop: ^0.6.0
  file_picker: ^10.1.9
  fluent_ui: ^4.11.3
  flutter:
    sdk: flutter
  flutter_midi_command: ^0.5.3
  flutter_riverpod: ^2.6.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  logger: ^2.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
  
