name: Flutter Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.build_target.os }}
    strategy:
      matrix:
        build_target:
          - { os: ubuntu-latest, platform: linux }
          - { os: ubuntu-latest, platform: android }
          - { os: windows-latest, platform: windows }

    env:
      PLATFORM: ${{ matrix.build_target.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build App
        run: |
          if [ "$PLATFORM" == "linux" ]; then
            flutter build linux --release
          elif [ "$PLATFORM" == "android" ]; then
            flutter build apk --release
          elif [ "$PLATFORM" == "windows" ]; then
            flutter build windows --release
          fi

      - name: Check Linux build output
        if: env.PLATFORM == 'linux'
        run: ls -la build/linux/x64/release/bundle/

      - name: Check Android build output
        if: env.PLATFORM == 'android'
        run: ls -la build/app/outputs/flutter-apk/

      - name: Check Windows build output
        if: env.PLATFORM == 'windows'
        run: dir build/windows/x64/runner/Release/

      - name: Archive Linux release
        if: env.PLATFORM == 'linux'
        run: |
          cd build/linux/x64/release/
          zip -r ../../../linux-release.zip bundle

      - name: Archive Windows release
        if: env.PLATFORM == 'windows'
        run: |
          cd build/windows/x64/runner/Release/
          zip -r ../../../../../windows-release.zip *

      - name: Upload Linux Artifact
        if: env.PLATFORM == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/linux-release.zip

      - name: Upload Windows Artifact
        if: env.PLATFORM == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: windows-release.zip

      - name: Upload Android APK
        if: env.PLATFORM == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Set release name
        id: release_name
        run: echo "name=release-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_name.outputs.name }}
          release_name: Release ${{ steps.release_name.outputs.name }}
          draft: false
          prerelease: false

      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/linux-release/build/linux-release.zip
          asset_name: linux-release.zip
          asset_content_type: application/zip

      - name: Upload Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows-release/windows-release.zip
          asset_name: windows-release.zip
          asset_content_type: application/zip

      - name: Upload Android APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/android-release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive